# ==================== [SECTION] SETTINGS ====================
# > [MenuType] : String | Represents the menu type. Allowed values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/MenuType.html
# > [Title] : String | Sets menu title.
# > [Auto_Refresh] : Integer | Defines menu refresh rate in seconds. Set 0 to disable.
# > [PlaceholderAPI -> Enabled] : Boolean | When enabled, applies PlaceholderAPI placeholders for all items in the menu per player.
#  
# ==================== [SECTION] CONTENT ====================
# You can freely edit items in this section as you wish (add, remove, modify items).
# > [Item] : Section | Item to display.
#     [*] Navigate to https://nightexpressdev.com/nightcore/configuration/item-formation/ for a list of available options.
# > [Priority] : Integer | Item priority. Higher values will override other item(s) in the same slot(s).
# > [Slots] : Int Array | Item slots, starts from 0. Split with commas.
#     Slots: '0,4,9,10'
# > [Type] : String | Defines item click action.
#     [*] Available types: ['close', 'user_skin', 'return', 'page_next', 'page_previous', 'sell_all']
# > [Click_Commands] : Section | Executes commands on click with PlaceholderAPI support.
#     [*] Works only if [Type] is not set (null).
#     [*] Available click types: [LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, DROP_KEY, SWAP_KEY, DRAG_N_DROP]
#     [*] Use prefix 'player:' to run command by a player.
#     Click_Commands:
#       LEFT:
#       - say Hello
#       - give %player_name% diamond 1
#       - player: warp shop
# ==================================================
Settings:
  MenuType: minecraft:generic_9x6
  Title: <c:#3E3E3E>Shop → %shop_name% (<white>%page%</white>/<white>%pages%</white>)</c>
  Auto_Refresh: -1
  PlaceholderAPI:
    Enabled: true
Content:
  gray_stained_glass_pane:
    Priority: -1
    Item:
      Material: minecraft:gray_stained_glass_pane
      Lore: []
      Hide_Tooltip: true
    Slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53
    Type: 'null'
  return:
    Priority: 10
    Item:
      Material: minecraft:iron_door
      Display_Name: <soft_yellow><b>Back</b></soft_yellow>
      Lore: []
    Slots: '49'
    Type: return
  page_next:
    Priority: 10
    Item:
      Material: minecraft:arrow
      Display_Name: <white><b><u>Next Page</u> →</b></white>
      Lore: []
    Slots: '50'
    Type: page_next
  page_previous:
    Priority: 10
    Item:
      Material: minecraft:arrow
      Display_Name: <white><b>← <u>Previous Page</u></b></white>
      Lore: []
    Slots: '48'
    Type: page_previous
  sell_all:
    Priority: 10
    Item:
      Material: minecraft:player_head
      Display_Name: <c:#ebd12a><b>SELL ALL</b></c>
      Lore:
      - <lgray>Sells everything from your</lgray>
      - <lgray>inventory to all available shops.</lgray>
      - ''
      - '<lgray><c:#ebd12a>➥</c> Sell Multiplier: <c:#ebd12a>x%sell_multiplier%</c></lgray>'
      - ''
      - <c:#ebd12a>→ <b><u>CLICK</u></b> to sell</c>
      SkinURL: 9fd108383dfa5b02e86635609541520e4e158952d68c1c8f8f200ec7e88642d
    Slots: '52'
    Type: sell_all
  balance:
    Priority: 10
    Item:
      Material: minecraft:player_head
      Display_Name: <c:#7cf1de><b>BALANCE</b></c>
      Lore:
      - <lgray>Here's displayed how much</lgray>
      - <lgray>money you have.</lgray>
      - ''
      - <c:#7cf1de>➥</c> <white>%balance%</white>
      SkinURL: 3324a7d61ccd44b031744b517f911a5c461614b953b17f648282e147b29d10e
    Slots: '46'
    Type: 'null'
